nelmio_api_doc:
    documentation:
        info:
            title: Acilia Software
            description: Acilia Software exercise
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

        host_patterns:
            - ^api\.

    models:
        names:
             - { alias: Category, type: App\Entity\Category}
             - { alias: Product, type: App\Entity\Product}
