#index:
#    path: /
#    controller: App\Controller\DefaultController::index

products_featured:
    path: /product/featured
    methods: GET
    controller: App\Controller\ProductController::getFeaturedProducts

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }